spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: fiscaladmin
    password: Ec0PyqvD
    hikari:
      maximum-pool-size: 5
    url: jdbc:postgresql://10.5.2.48:5432/postgres

energosbyt:
  rabbit:
    host: 10.5.3.70
    port: 5672
    username: admin
    password: Etooshagh5
    input-queue: g_eremeev
    output-queue: g_eremeev_out
    error-queue: g_eremeev_error
    request:
      timeout-in-ms: 30000